{% set version = "0.8.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tangram
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tangram_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tangram/tangram_{{ version }}.tar.gz
  sha256: db7e3553313cf7b377bc81bb6c9401a4510569eb99a75fa2e945cc4d261fb0ee

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-base64enc
    - r-digest
    - r-htmltools
    - r-magrittr
    - r-knitr
    - r-stringi
    - r-stringr
  run:
    - r-base
    - r-r6
    - r-base64enc
    - r-digest
    - r-knitr
    - r-htmltools
    - r-magrittr
    - r-stringi
    - r-stringr

test:
  commands:
    - $R -e "library('tangram')"           # [not win]
    - "\"%R%\" -e \"library('tangram')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tangram
  license: GPL-3.0-only
  summary: Provides an extensible formula system to quickly and easily create production quality tables. The steps of the process are formula parser, statistical content generation from data, to rendering. Each step of the process is separate and user definable thus creating a set of building blocks for highly extensible
    table generation. A user is not limited by any of the  choices of the package creator other than the formula grammar. For example, one could chose to add a different S3 rendering function and output a format not provided in the default package. Or possibly one would rather have Gini coefficients for their statistical
    content. Routines to achieve New England Journal of Medicine style, Lancet style and Hmisc::summaryM() statistics are provided. The package contains rendering for HTML5, Rmarkdown and an indexing format for use in tracing and tracking are provided.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
