travis:
  secure:
    BINSTAR_TOKEN: PxGq88JKQD0PmH7iPurGNOedtD7OhNb6+YrmqkmTXpHLQPZaXd8iouzHEJgRsxrHTGQTqgV9E2VNhffB6QcoSV+eAaU6bdBr2jLBRWm1ow/7WylwDm6Z8DL3EXg4q419ui/xSIjb3SFomwa3mwQdZSreDdbLLL097kFunUG+UhVhTYbpDJ3YkMZ1hf5c/bRZpKvoTVLhTJWfu4aQEIO/54I3jOK+Q+iD4fVaoaTy/WDa7+X6r1Ph0gV8d2aclqjc76lcLdGrHnzYahiB8K7acpmg+Jmhj1794Tw6IzUCU62U3c5EMAyd7mGrjUNddtt4pkWb85RuEKSEo1EohWe25phrOvYBKlZWetdXmeA+W0FIbRnkOM9+UH4w58I06f1O8X4vZdQ+dv8rLSrjdwSXIJfv75Nw17dC4d+BwW281Q/8pfoHX7FSoB3Ov9n9S+fIZc+ViUg0uqkV0ppcD6X6cVUUz3BTPLwHqCJu70Oool2cuGqFsyv5pznRvwdNeqbTDz43qdE3i/jJ0zuyxKNTttSbUdyOtEGRkOLcsq8o7FcMMPyp4SBWS1ffwTaj2HBKcJZFALRMrzLrzI065pCfyBvS2j/F2PWFWo+klPpzeJhCjdQxvg38XEM6Ms/hRu39QFWDwl0WWrEw0hZApP++XL7AxqU1vnitTr20GmSAgTc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
